#!/usr/bin/env python3
"""Generate App/Design/DesignTokens.swift from brand/brand.json.

The chain is one-directional and has no manual step:

    brand/brand.json  ->  App/Design/DesignTokens.swift  ->  screen

A hex literal written by hand in a SwiftUI view is a bug, not a shortcut. If a value
does not exist as a token, add it to brand.json and re-run this.

    python scripts/gen-tokens.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "brand" / "brand.json"
OUT = ROOT / "App" / "Design" / "DesignTokens.swift"

# The HTML surfaces that consume the same tokens. Their :root blocks used to be typed
# by hand, which meant three copies of the palette and no way to notice when one
# drifted -- the flip to a light theme would have left two of them on the old dark
# values, and nothing would have said so.
CSS_TARGETS = [ROOT / "host" / "console.html",
               ROOT / "host" / "mockup.template.html",
               ROOT / "host" / "app.template.html"]
CSS_BEGIN = "  /* @tokens"
CSS_END = "  /* @end-tokens */"


def camel(name: str) -> str:
    parts = re.split(r"[-_ ]+", name)
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def rgb(hex_str: str):
    h = hex_str.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


FALLBACKS = {
    "display": '"Trebuchet MS", sans-serif',
    "body": 'ui-sans-serif, system-ui, -apple-system, "Helvetica Neue", sans-serif',
    "data": 'ui-monospace, "SF Mono", "Cascadia Mono", Menlo, monospace',
}


def css_block(colors, radii, durations, typography) -> str:
    """The generated half of a :root block, indented to sit inside one."""
    out = [
        "  /* @tokens - generated by scripts/gen-tokens.py from brand/brand.json.",
        "     Do not edit by hand: add the value to the JSON and re-run. */",
    ]
    out += [f"  --color-{name}: {value};" for name, value in colors.items()]
    out.append("")
    out += [f"  --radius-{name}: {value}px;"
            for name, value in zip(["viewport", "panel", "pill"], radii)]
    out.append("")
    out += [f"  --duration-{name}: {ms}ms;" for name, ms in durations.items()]
    out.append("")
    out += [f'  --font-{role}: "{family}", {FALLBACKS.get(role, "sans-serif")};'
            for role, family in typography.items()]
    out.append(CSS_END)
    return "\n".join(out)


def write_css(colors, radii, durations, typography) -> int:
    """Rewrite the generated span of every consuming page's :root block."""
    block = css_block(colors, radii, durations, typography)
    written = 0
    for target in CSS_TARGETS:
        if not target.exists():
            continue
        text = target.read_text(encoding="utf-8")
        start, end = text.find(CSS_BEGIN), text.find(CSS_END)
        if start < 0 or end < 0:
            print(f"FAIL: {target.name} has no @tokens / @end-tokens markers in :root",
                  file=sys.stderr)
            return -1
        target.write_text(text[:start] + block + text[end + len(CSS_END):], encoding="utf-8")
        written += 1
    return written


def main() -> int:
    brand = json.loads(BRAND.read_text(encoding="utf-8"))
    colors = brand["colors"]
    radii = brand["radius"]
    durations = brand["motion"]["durations"]
    typography = brand["typography"]

    lines = [
        "// GENERATED FILE - DO NOT EDIT.",
        "// Source: brand/brand.json   Regenerate: python scripts/gen-tokens.py",
        "//",
        "// Every colour, radius, duration and font in the app comes from here. A hex",
        "// literal in a view is a bug; add the value to brand.json instead.",
        "",
        "import SwiftUI",
        "",
        "public enum Token {",
        "",
        "    // MARK: Colour",
        "",
        "    public enum Color {",
    ]

    for name, hex_str in colors.items():
        r, g, b = rgb(hex_str)
        lines.append(
            f"        /// {hex_str}\n"
            f"        public static let {camel(name)} = SwiftUI.Color("
            f"red: {r:.4f}, green: {g:.4f}, blue: {b:.4f})"
        )

    lines += [
        "    }",
        "",
        "    // MARK: Radius - three values, and only three",
        "",
        "    public enum Radius {",
    ]
    radius_names = ["viewport", "panel", "pill"]
    for name, value in zip(radius_names, radii):
        lines.append(f"        public static let {name}: CGFloat = {value}")

    lines += [
        "    }",
        "",
        "    // MARK: Motion - the fixed scale, no intermediate values",
        "",
        "    public enum Duration {",
    ]
    for name, ms in durations.items():
        lines.append(f"        /// {ms}ms\n        public static let {name}: Double = {ms / 1000:.3f}")

    lines += [
        "    }",
        "",
        "    // MARK: Type",
        "",
        "    public enum Typeface {",
        f'        /// {typography["display"]}, bundled. Variable font; its default',
        "        /// instance is the wide extrabold at a large optical size.",
        '        public static let display = "BricolageGrotesque-96ptExtraBold"',
        "    }",
        "}",
        "",
        "public extension Font {",
        "    /// Display face. Used for the health number and screen titles only.",
        "    static func mushDisplay(_ size: CGFloat) -> Font {",
        "        .custom(Token.Typeface.display, size: size)",
        "    }",
        "",
        "    /// Instrument label: tiny, uppercase, wide-tracked. Pair with .tracking(0.8).",
        "    static func mushLabel() -> Font {",
        "        .system(size: 11, weight: .semibold)",
        "    }",
        "",
        "    /// Numbers that must line up in a column.",
        "    static func mushData(_ size: CGFloat = 14) -> Font {",
        "        .system(size: size, weight: .medium, design: .monospaced)",
        "    }",
        "}",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    pages = write_css(colors, radii, durations, typography)
    if pages < 0:
        return 2

    print(f"wrote {OUT.relative_to(ROOT)}  ({len(colors)} colours, "
          f"{len(radii)} radii, {len(durations)} durations)"
          f" + the :root block in {pages} page(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
